apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  {{ template "name" . }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.image.tag }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ template "name" . }}
spec:
  hosts:
  - "*"
  gateways:
  - core-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ template "name" . }}
        port:
          number: 8080
