apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  nifi
spec:
  hosts:
  - "nifi.dev.andesml.com"
  gateways:
  - nifi
  http:
  - match:
    - uri:
        prefix:
    rewrite:
      uri: /nifi
    route:
    - destination:
        host: nifi
        port:
          number: 8080